---
- name: Install revproxytunnel env
  become: true
  ansible.builtin.apt:
    package:
      - docker.io
    state: present

- name: Start revproxytunnel env
  become: true
  ansible.builtin.systemd_service:
    unit: docker
    state: started
    daemon_reload: true
